services:
  - type: web
    name: alerting-platform-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /

  - type: web
    name: alerting-platform-frontend
    env: node
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: alerting-platform-backend
          property: host